### ISSUE TITLE
Errors seem to be occurring on A02s and A11s messages.

### ISSUE THREAD

**Issue by MihaiSandor** [kardianos/hl7#2]
@kardianos When I try to parse this message with v2.5 I got this error: `invalid characters in date: "10005218^^^default^default"`

`MSH|^~\&|PATIENTPING_ADT|272605^Regional Medical CPID|1|p-d507c951-96f3-11ed-96e0-39b4d2a37a61^^^PP^PP|10005218^^^default^default||JOE^DOE^||19541129|F|||31 MOZFA|272605|UNC Regional Medical|HOS|300 W 27th St^^Hometown^NC^28358|1790152668210992`.

Did you have any idea why on messages `A02s` and `A11s` is a problem?

**Comment by MihaiSandor** [comment]
Here is the Go Playground example: https://go.dev/play/p/7b-xGO9A9Xo

**Comment by kardianos** [comment]
The issue is that the TS data type should technically be a struct where the first field is a time stamp, but I've simplified it to `type TS = time.Time`. Thus it is attempting to parse the entire field of `10005218^^^default^default` as a time, not just the first part. An easy fix would be for the parser to first use `strings.Cut(field, "^") and take the first part of the message. I'll see if I can update that logic.

**Comment by MihaiSandor** [comment]
I think not it is ok, but the date was not changed by myself, it is exactly how I got it from Bamboo. I will check with Bamboo this problem.
